<?php

namespace Database\Seeders;

use App\Models\Pais;
use Illuminate\Database\Seeder;

class Paises extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Pais::create(['id' => 3, 'nome' => 'África do Sul', 'codigo_area' => '+55']);
        Pais::create(['id' => 4, 'nome' => 'Akrotiri', 'codigo_area' => '+55']);
        Pais::create(['id' => 5, 'nome' => 'Albânia', 'codigo_area' => '+55']);
        Pais::create(['id' => 6, 'nome' => 'Alemanha', 'codigo_area' => '+55']);
        Pais::create(['id' => 7, 'nome' => 'Andorra', 'codigo_area' => '+55']);
        Pais::create(['id' => 8, 'nome' => 'Angola', 'codigo_area' => '+55']);
        Pais::create(['id' => 9, 'nome' => 'Anguila', 'codigo_area' => '+55']);
        Pais::create(['id' => 10, 'nome' => 'Antárctida', 'codigo_area' => '+55']);
        Pais::create(['id' => 11, 'nome' => 'Antígua e Barbuda', 'codigo_area' => '+55']);
        Pais::create(['id' => 12, 'nome' => 'Antilhas Neerlandesas', 'codigo_area' => '+55']);
        Pais::create(['id' => 13, 'nome' => 'Arábia Saudita', 'codigo_area' => '+55']);
        Pais::create(['id' => 14, 'nome' => 'Arctic Ocean', 'codigo_area' => '+55']);
        Pais::create(['id' => 15, 'nome' => 'Argélia', 'codigo_area' => '+55']);
        Pais::create(['id' => 16, 'nome' => 'Argentina', 'codigo_area' => '+55']);
        Pais::create(['id' => 17, 'nome' => 'Arménia', 'codigo_area' => '+55']);
        Pais::create(['id' => 18, 'nome' => 'Aruba', 'codigo_area' => '+55']);
        Pais::create(['id' => 19, 'nome' => 'Ashmore and Cartier Islands', 'codigo_area' => '+55']);
        Pais::create(['id' => 20, 'nome' => 'Atlantic Ocean', 'codigo_area' => '+55']);
        Pais::create(['id' => 21, 'nome' => 'Austrália', 'codigo_area' => '+55']);
        Pais::create(['id' => 22, 'nome' => 'Áustria', 'codigo_area' => '+55']);
        Pais::create(['id' => 23, 'nome' => 'Azerbaijão', 'codigo_area' => '+55']);
        Pais::create(['id' => 24, 'nome' => 'Baamas', 'codigo_area' => '+55']);
        Pais::create(['id' => 25, 'nome' => 'Bangladeche', 'codigo_area' => '+55']);
        Pais::create(['id' => 26, 'nome' => 'Barbados', 'codigo_area' => '+55']);
        Pais::create(['id' => 27, 'nome' => 'Barém', 'codigo_area' => '+55']);
        Pais::create(['id' => 28, 'nome' => 'Bélgica', 'codigo_area' => '+55']);
        Pais::create(['id' => 29, 'nome' => 'Belize', 'codigo_area' => '+55']);
        Pais::create(['id' => 30, 'nome' => 'Benim', 'codigo_area' => '+55']);
        Pais::create(['id' => 31, 'nome' => 'Bermudas', 'codigo_area' => '+55']);
        Pais::create(['id' => 32, 'nome' => 'Bielorrússia', 'codigo_area' => '+55']);
        Pais::create(['id' => 33, 'nome' => 'Birmânia', 'codigo_area' => '+55']);
        Pais::create(['id' => 34, 'nome' => 'Bolívia', 'codigo_area' => '+55']);
        Pais::create(['id' => 35, 'nome' => 'Bósnia e Herzegovina', 'codigo_area' => '+55']);
        Pais::create(['id' => 36, 'nome' => 'Botsuana', 'codigo_area' => '+55']);
        Pais::create(['id' => 37, 'nome' => 'Brasil', 'codigo_area' => '+55']);
        Pais::create(['id' => 38, 'nome' => 'Brunei', 'codigo_area' => '+55']);
        Pais::create(['id' => 39, 'nome' => 'Bulgária', 'codigo_area' => '+55']);
        Pais::create(['id' => 40, 'nome' => 'Burquina Faso', 'codigo_area' => '+55']);
        Pais::create(['id' => 41, 'nome' => 'Burúndi', 'codigo_area' => '+55']);
        Pais::create(['id' => 42, 'nome' => 'Butão', 'codigo_area' => '+55']);
        Pais::create(['id' => 43, 'nome' => 'Cabo Verde', 'codigo_area' => '+55']);
        Pais::create(['id' => 44, 'nome' => 'Camarões', 'codigo_area' => '+55']);
        Pais::create(['id' => 45, 'nome' => 'Camboja', 'codigo_area' => '+55']);
        Pais::create(['id' => 46, 'nome' => 'Canadá', 'codigo_area' => '+55']);
        Pais::create(['id' => 47, 'nome' => 'Catar', 'codigo_area' => '+55']);
        Pais::create(['id' => 48, 'nome' => 'Cazaquistão', 'codigo_area' => '+55']);
        Pais::create(['id' => 49, 'nome' => 'Chade', 'codigo_area' => '+55']);
        Pais::create(['id' => 50, 'nome' => 'Chile', 'codigo_area' => '+55']);
        Pais::create(['id' => 51, 'nome' => 'China', 'codigo_area' => '+55']);
        Pais::create(['id' => 52, 'nome' => 'Chipre', 'codigo_area' => '+55']);
        Pais::create(['id' => 53, 'nome' => 'Clipperton Island', 'codigo_area' => '+55']);
        Pais::create(['id' => 54, 'nome' => 'Colômbia', 'codigo_area' => '+55']);
        Pais::create(['id' => 55, 'nome' => 'Comores', 'codigo_area' => '+55']);
        Pais::create(['id' => 56, 'nome' => 'Congo-Brazzaville', 'codigo_area' => '+55']);
        Pais::create(['id' => 57, 'nome' => 'Congo-Kinshasa', 'codigo_area' => '+55']);
        Pais::create(['id' => 58, 'nome' => 'Coral Sea Islands', 'codigo_area' => '+55']);
        Pais::create(['id' => 59, 'nome' => 'Coreia do Norte', 'codigo_area' => '+55']);
        Pais::create(['id' => 60, 'nome' => 'Coreia do Sul', 'codigo_area' => '+55']);
        Pais::create(['id' => 61, 'nome' => 'Costa do Marfim', 'codigo_area' => '+55']);
        Pais::create(['id' => 62, 'nome' => 'Costa Rica', 'codigo_area' => '+55']);
        Pais::create(['id' => 63, 'nome' => 'Croácia', 'codigo_area' => '+55']);
        Pais::create(['id' => 64, 'nome' => 'Cuba', 'codigo_area' => '+55']);
        Pais::create(['id' => 65, 'nome' => 'Dhekelia', 'codigo_area' => '+55']);
        Pais::create(['id' => 66, 'nome' => 'Dinamarca', 'codigo_area' => '+55']);
        Pais::create(['id' => 67, 'nome' => 'Domínica', 'codigo_area' => '+55']);
        Pais::create(['id' => 68, 'nome' => 'Egipto', 'codigo_area' => '+55']);
        Pais::create(['id' => 69, 'nome' => 'Emiratos Árabes Unidos', 'codigo_area' => '+55']);
        Pais::create(['id' => 70, 'nome' => 'Equador', 'codigo_area' => '+55']);
        Pais::create(['id' => 71, 'nome' => 'Eritreia', 'codigo_area' => '+55']);
        Pais::create(['id' => 72, 'nome' => 'Eslováquia', 'codigo_area' => '+55']);
        Pais::create(['id' => 73, 'nome' => 'Eslovénia', 'codigo_area' => '+55']);
        Pais::create(['id' => 74, 'nome' => 'Espanha', 'codigo_area' => '+55']);
        Pais::create(['id' => 75, 'nome' => 'Estados Unidos', 'codigo_area' => '+55']);
        Pais::create(['id' => 76, 'nome' => 'Estónia', 'codigo_area' => '+55']);
        Pais::create(['id' => 77, 'nome' => 'Etiópia', 'codigo_area' => '+55']);
        Pais::create(['id' => 78, 'nome' => 'Faroé', 'codigo_area' => '+55']);
        Pais::create(['id' => 79, 'nome' => 'Fiji', 'codigo_area' => '+55']);
        Pais::create(['id' => 80, 'nome' => 'Filipinas', 'codigo_area' => '+55']);
        Pais::create(['id' => 81, 'nome' => 'Finlândia', 'codigo_area' => '+55']);
        Pais::create(['id' => 82, 'nome' => 'França', 'codigo_area' => '+55']);
        Pais::create(['id' => 83, 'nome' => 'Gabão', 'codigo_area' => '+55']);
        Pais::create(['id' => 84, 'nome' => 'Gâmbia', 'codigo_area' => '+55']);
        Pais::create(['id' => 85, 'nome' => 'Gana', 'codigo_area' => '+55']);
        Pais::create(['id' => 86, 'nome' => 'Gaza Strip', 'codigo_area' => '+55']);
        Pais::create(['id' => 87, 'nome' => 'Geórgia', 'codigo_area' => '+55']);
        Pais::create(['id' => 88, 'nome' => 'Geórgia do Sul e Sandwich do Sul', 'codigo_area' => '+55']);
        Pais::create(['id' => 89, 'nome' => 'Gibraltar', 'codigo_area' => '+55']);
        Pais::create(['id' => 90, 'nome' => 'Granada', 'codigo_area' => '+55']);
        Pais::create(['id' => 91, 'nome' => 'Grécia', 'codigo_area' => '+55']);
        Pais::create(['id' => 92, 'nome' => 'Gronelândia', 'codigo_area' => '+55']);
        Pais::create(['id' => 93, 'nome' => 'Guame', 'codigo_area' => '+55']);
        Pais::create(['id' => 94, 'nome' => 'Guatemala', 'codigo_area' => '+55']);
        Pais::create(['id' => 95, 'nome' => 'Guernsey', 'codigo_area' => '+55']);
        Pais::create(['id' => 96, 'nome' => 'Guiana', 'codigo_area' => '+55']);
        Pais::create(['id' => 97, 'nome' => 'Guiné', 'codigo_area' => '+55']);
        Pais::create(['id' => 98, 'nome' => 'Guiné Equatorial', 'codigo_area' => '+55']);
        Pais::create(['id' => 99, 'nome' => 'Guiné-Bissau', 'codigo_area' => '+55']);
        Pais::create(['id' => 100, 'nome' => 'Haiti', 'codigo_area' => '+55']);
        Pais::create(['id' => 101, 'nome' => 'Honduras', 'codigo_area' => '+55']);
        Pais::create(['id' => 102, 'nome' => 'Hong Kong', 'codigo_area' => '+55']);
        Pais::create(['id' => 103, 'nome' => 'Hungria', 'codigo_area' => '+55']);
        Pais::create(['id' => 104, 'nome' => 'Iémen', 'codigo_area' => '+55']);
        Pais::create(['id' => 105, 'nome' => 'Ilha Bouvet', 'codigo_area' => '+55']);
        Pais::create(['id' => 106, 'nome' => 'Ilha do Natal', 'codigo_area' => '+55']);
        Pais::create(['id' => 107, 'nome' => 'Ilha Norfolk', 'codigo_area' => '+55']);
        Pais::create(['id' => 108, 'nome' => 'Ilhas Caimão', 'codigo_area' => '+55']);
        Pais::create(['id' => 109, 'nome' => 'Ilhas Cook', 'codigo_area' => '+55']);
        Pais::create(['id' => 110, 'nome' => 'Ilhas dos Cocos', 'codigo_area' => '+55']);
        Pais::create(['id' => 111, 'nome' => 'Ilhas Falkland', 'codigo_area' => '+55']);
        Pais::create(['id' => 112, 'nome' => 'Ilhas Heard e McDonald', 'codigo_area' => '+55']);
        Pais::create(['id' => 113, 'nome' => 'Ilhas Marshall', 'codigo_area' => '+55']);
        Pais::create(['id' => 114, 'nome' => 'Ilhas Salomão', 'codigo_area' => '+55']);
        Pais::create(['id' => 115, 'nome' => 'Ilhas Turcas e Caicos', 'codigo_area' => '+55']);
        Pais::create(['id' => 116, 'nome' => 'Ilhas Virgens Americanas', 'codigo_area' => '+55']);
        Pais::create(['id' => 117, 'nome' => 'Ilhas Virgens Britânicas', 'codigo_area' => '+55']);
        Pais::create(['id' => 118, 'nome' => 'Índia', 'codigo_area' => '+55']);
        Pais::create(['id' => 119, 'nome' => 'Indian Ocean', 'codigo_area' => '+55']);
        Pais::create(['id' => 120, 'nome' => 'Indonésia', 'codigo_area' => '+55']);
        Pais::create(['id' => 121, 'nome' => 'Irão', 'codigo_area' => '+55']);
        Pais::create(['id' => 122, 'nome' => 'Iraque', 'codigo_area' => '+55']);
        Pais::create(['id' => 123, 'nome' => 'Irlanda', 'codigo_area' => '+55']);
        Pais::create(['id' => 124, 'nome' => 'Islândia', 'codigo_area' => '+55']);
        Pais::create(['id' => 125, 'nome' => 'Israel', 'codigo_area' => '+55']);
        Pais::create(['id' => 126, 'nome' => 'Itália', 'codigo_area' => '+55']);
        Pais::create(['id' => 127, 'nome' => 'Jamaica', 'codigo_area' => '+55']);
        Pais::create(['id' => 128, 'nome' => 'Jan Mayen', 'codigo_area' => '+55']);
        Pais::create(['id' => 129, 'nome' => 'Japão', 'codigo_area' => '+55']);
        Pais::create(['id' => 130, 'nome' => 'Jersey', 'codigo_area' => '+55']);
        Pais::create(['id' => 131, 'nome' => 'Jibuti', 'codigo_area' => '+55']);
        Pais::create(['id' => 132, 'nome' => 'Jordânia', 'codigo_area' => '+55']);
        Pais::create(['id' => 133, 'nome' => 'Kuwait', 'codigo_area' => '+55']);
        Pais::create(['id' => 134, 'nome' => 'Laos', 'codigo_area' => '+55']);
        Pais::create(['id' => 135, 'nome' => 'Lesoto', 'codigo_area' => '+55']);
        Pais::create(['id' => 136, 'nome' => 'Letónia', 'codigo_area' => '+55']);
        Pais::create(['id' => 137, 'nome' => 'Líbano', 'codigo_area' => '+55']);
        Pais::create(['id' => 138, 'nome' => 'Libéria', 'codigo_area' => '+55']);
        Pais::create(['id' => 139, 'nome' => 'Líbia', 'codigo_area' => '+55']);
        Pais::create(['id' => 140, 'nome' => 'Listenstaine', 'codigo_area' => '+55']);
        Pais::create(['id' => 141, 'nome' => 'Lituânia', 'codigo_area' => '+55']);
        Pais::create(['id' => 142, 'nome' => 'Luxemburgo', 'codigo_area' => '+55']);
        Pais::create(['id' => 143, 'nome' => 'Macau', 'codigo_area' => '+55']);
        Pais::create(['id' => 144, 'nome' => 'Macedónia', 'codigo_area' => '+55']);
        Pais::create(['id' => 145, 'nome' => 'Madagáscar', 'codigo_area' => '+55']);
        Pais::create(['id' => 146, 'nome' => 'Malásia', 'codigo_area' => '+55']);
        Pais::create(['id' => 147, 'nome' => 'Malávi', 'codigo_area' => '+55']);
        Pais::create(['id' => 148, 'nome' => 'Maldivas', 'codigo_area' => '+55']);
        Pais::create(['id' => 149, 'nome' => 'Mali', 'codigo_area' => '+55']);
        Pais::create(['id' => 150, 'nome' => 'Malta', 'codigo_area' => '+55']);
        Pais::create(['id' => 151, 'nome' => 'Man, Isle of', 'codigo_area' => '+55']);
        Pais::create(['id' => 152, 'nome' => 'Marianas do Norte', 'codigo_area' => '+55']);
        Pais::create(['id' => 153, 'nome' => 'Marrocos', 'codigo_area' => '+55']);
        Pais::create(['id' => 154, 'nome' => 'Maurícia', 'codigo_area' => '+55']);
        Pais::create(['id' => 155, 'nome' => 'Mauritânia', 'codigo_area' => '+55']);
        Pais::create(['id' => 156, 'nome' => 'Mayotte', 'codigo_area' => '+55']);
        Pais::create(['id' => 157, 'nome' => 'México', 'codigo_area' => '+55']);
        Pais::create(['id' => 158, 'nome' => 'Micronésia', 'codigo_area' => '+55']);
        Pais::create(['id' => 159, 'nome' => 'Moçambique', 'codigo_area' => '+55']);
        Pais::create(['id' => 160, 'nome' => 'Moldávia', 'codigo_area' => '+55']);
        Pais::create(['id' => 161, 'nome' => 'Mónaco', 'codigo_area' => '+55']);
        Pais::create(['id' => 162, 'nome' => 'Mongólia', 'codigo_area' => '+55']);
        Pais::create(['id' => 163, 'nome' => 'Monserrate', 'codigo_area' => '+55']);
        Pais::create(['id' => 164, 'nome' => 'Montenegro', 'codigo_area' => '+55']);
        Pais::create(['id' => 165, 'nome' => 'Mundo', 'codigo_area' => '+55']);
        Pais::create(['id' => 166, 'nome' => 'Namíbia', 'codigo_area' => '+55']);
        Pais::create(['id' => 167, 'nome' => 'Nauru', 'codigo_area' => '+55']);
        Pais::create(['id' => 168, 'nome' => 'Navassa Island', 'codigo_area' => '+55']);
        Pais::create(['id' => 169, 'nome' => 'Nepal', 'codigo_area' => '+55']);
        Pais::create(['id' => 170, 'nome' => 'Nicarágua', 'codigo_area' => '+55']);
        Pais::create(['id' => 171, 'nome' => 'Níger', 'codigo_area' => '+55']);
        Pais::create(['id' => 172, 'nome' => 'Nigéria', 'codigo_area' => '+55']);
        Pais::create(['id' => 173, 'nome' => 'Niue', 'codigo_area' => '+55']);
        Pais::create(['id' => 174, 'nome' => 'Noruega', 'codigo_area' => '+55']);
        Pais::create(['id' => 175, 'nome' => 'Nova Caledónia', 'codigo_area' => '+55']);
        Pais::create(['id' => 176, 'nome' => 'Nova Zelândia', 'codigo_area' => '+55']);
        Pais::create(['id' => 177, 'nome' => 'Omã', 'codigo_area' => '+55']);
        Pais::create(['id' => 178, 'nome' => 'Pacific Ocean', 'codigo_area' => '+55']);
        Pais::create(['id' => 179, 'nome' => 'Países Baixos', 'codigo_area' => '+55']);
        Pais::create(['id' => 180, 'nome' => 'Palau', 'codigo_area' => '+55']);
        Pais::create(['id' => 181, 'nome' => 'Panamá', 'codigo_area' => '+55']);
        Pais::create(['id' => 182, 'nome' => 'Papua-Nova Guiné', 'codigo_area' => '+55']);
        Pais::create(['id' => 183, 'nome' => 'Paquistão', 'codigo_area' => '+55']);
        Pais::create(['id' => 184, 'nome' => 'Paracel Islands', 'codigo_area' => '+55']);
        Pais::create(['id' => 185, 'nome' => 'Paraguai', 'codigo_area' => '+55']);
        Pais::create(['id' => 186, 'nome' => 'Peru', 'codigo_area' => '+55']);
        Pais::create(['id' => 187, 'nome' => 'Pitcairn', 'codigo_area' => '+55']);
        Pais::create(['id' => 188, 'nome' => 'Polinésia Francesa', 'codigo_area' => '+55']);
        Pais::create(['id' => 189, 'nome' => 'Polónia', 'codigo_area' => '+55']);
        Pais::create(['id' => 190, 'nome' => 'Porto Rico', 'codigo_area' => '+55']);
        Pais::create(['id' => 191, 'nome' => 'Portugal', 'codigo_area' => '+55']);
        Pais::create(['id' => 192, 'nome' => 'Quénia', 'codigo_area' => '+55']);
        Pais::create(['id' => 193, 'nome' => 'Quirguizistão', 'codigo_area' => '+55']);
        Pais::create(['id' => 194, 'nome' => 'Quiribáti', 'codigo_area' => '+55']);
        Pais::create(['id' => 195, 'nome' => 'Reino Unido', 'codigo_area' => '+55']);
        Pais::create(['id' => 196, 'nome' => 'República Centro-Africana', 'codigo_area' => '+55']);
        Pais::create(['id' => 197, 'nome' => 'República Checa', 'codigo_area' => '+55']);
        Pais::create(['id' => 198, 'nome' => 'República Dominicana', 'codigo_area' => '+55']);
        Pais::create(['id' => 199, 'nome' => 'Roménia', 'codigo_area' => '+55']);
        Pais::create(['id' => 200, 'nome' => 'Ruanda', 'codigo_area' => '+55']);
        Pais::create(['id' => 201, 'nome' => 'Rússia', 'codigo_area' => '+55']);
        Pais::create(['id' => 202, 'nome' => 'Salvador', 'codigo_area' => '+55']);
        Pais::create(['id' => 203, 'nome' => 'Samoa', 'codigo_area' => '+55']);
        Pais::create(['id' => 204, 'nome' => 'Samoa Americana', 'codigo_area' => '+55']);
        Pais::create(['id' => 205, 'nome' => 'Santa Helena', 'codigo_area' => '+55']);
        Pais::create(['id' => 206, 'nome' => 'Santa Lúcia', 'codigo_area' => '+55']);
        Pais::create(['id' => 207, 'nome' => 'São Cristóvão e Neves', 'codigo_area' => '+55']);
        Pais::create(['id' => 208, 'nome' => 'São Marinho', 'codigo_area' => '+55']);
        Pais::create(['id' => 209, 'nome' => 'São Pedro e Miquelon', 'codigo_area' => '+55']);
        Pais::create(['id' => 210, 'nome' => 'São Tomé e Príncipe', 'codigo_area' => '+55']);
        Pais::create(['id' => 211, 'nome' => 'São Vicente e Granadinas', 'codigo_area' => '+55']);
        Pais::create(['id' => 212, 'nome' => 'Sara Ocidental', 'codigo_area' => '+55']);
        Pais::create(['id' => 213, 'nome' => 'Seicheles', 'codigo_area' => '+55']);
        Pais::create(['id' => 214, 'nome' => 'Senegal', 'codigo_area' => '+55']);
        Pais::create(['id' => 215, 'nome' => 'Serra Leoa', 'codigo_area' => '+55']);
        Pais::create(['id' => 216, 'nome' => 'Sérvia', 'codigo_area' => '+55']);
        Pais::create(['id' => 217, 'nome' => 'Singapura', 'codigo_area' => '+55']);
        Pais::create(['id' => 218, 'nome' => 'Síria', 'codigo_area' => '+55']);
        Pais::create(['id' => 219, 'nome' => 'Somália', 'codigo_area' => '+55']);
        Pais::create(['id' => 220, 'nome' => 'Southern Ocean', 'codigo_area' => '+55']);
        Pais::create(['id' => 221, 'nome' => 'Spratly Islands', 'codigo_area' => '+55']);
        Pais::create(['id' => 222, 'nome' => 'Sri Lanca', 'codigo_area' => '+55']);
        Pais::create(['id' => 223, 'nome' => 'Suazilândia', 'codigo_area' => '+55']);
        Pais::create(['id' => 224, 'nome' => 'Sudão', 'codigo_area' => '+55']);
        Pais::create(['id' => 225, 'nome' => 'Suécia', 'codigo_area' => '+55']);
        Pais::create(['id' => 226, 'nome' => 'Suíça', 'codigo_area' => '+55']);
        Pais::create(['id' => 227, 'nome' => 'Suriname', 'codigo_area' => '+55']);
        Pais::create(['id' => 228, 'nome' => 'Svalbard e Jan Mayen', 'codigo_area' => '+55']);
        Pais::create(['id' => 229, 'nome' => 'Tailândia', 'codigo_area' => '+55']);
        Pais::create(['id' => 230, 'nome' => 'Taiwan', 'codigo_area' => '+55']);
        Pais::create(['id' => 231, 'nome' => 'Tajiquistão', 'codigo_area' => '+55']);
        Pais::create(['id' => 232, 'nome' => 'Tanzânia', 'codigo_area' => '+55']);
        Pais::create(['id' => 233, 'nome' => 'Território Britânico do Oceano Índico', 'codigo_area' => '+55']);
        Pais::create(['id' => 234, 'nome' => 'Territórios Austrais Franceses', 'codigo_area' => '+55']);
        Pais::create(['id' => 235, 'nome' => 'Timor Leste', 'codigo_area' => '+55']);
        Pais::create(['id' => 236, 'nome' => 'Togo', 'codigo_area' => '+55']);
        Pais::create(['id' => 237, 'nome' => 'Tokelau', 'codigo_area' => '+55']);
        Pais::create(['id' => 238, 'nome' => 'Tonga', 'codigo_area' => '+55']);
        Pais::create(['id' => 239, 'nome' => 'Trindade e Tobago', 'codigo_area' => '+55']);
        Pais::create(['id' => 240, 'nome' => 'Tunísia', 'codigo_area' => '+55']);
        Pais::create(['id' => 241, 'nome' => 'Turquemenistão', 'codigo_area' => '+55']);
        Pais::create(['id' => 242, 'nome' => 'Turquia', 'codigo_area' => '+55']);
        Pais::create(['id' => 243, 'nome' => 'Tuvalu', 'codigo_area' => '+55']);
        Pais::create(['id' => 244, 'nome' => 'Ucrânia', 'codigo_area' => '+55']);
        Pais::create(['id' => 245, 'nome' => 'Uganda', 'codigo_area' => '+55']);
        Pais::create(['id' => 246, 'nome' => 'União Europeia', 'codigo_area' => '+55']);
        Pais::create(['id' => 247, 'nome' => 'Uruguai', 'codigo_area' => '+55']);
        Pais::create(['id' => 248, 'nome' => 'Usbequistão', 'codigo_area' => '+55']);
        Pais::create(['id' => 249, 'nome' => 'Vanuatu', 'codigo_area' => '+55']);
        Pais::create(['id' => 250, 'nome' => 'Vaticano', 'codigo_area' => '+55']);
        Pais::create(['id' => 251, 'nome' => 'Venezuela', 'codigo_area' => '+55']);
        Pais::create(['id' => 252, 'nome' => 'Vietname', 'codigo_area' => '+55']);
        Pais::create(['id' => 253, 'nome' => 'Wake Island', 'codigo_area' => '+55']);
        Pais::create(['id' => 254, 'nome' => 'Wallis e Futuna', 'codigo_area' => '+55']);
        Pais::create(['id' => 255, 'nome' => 'West Bank', 'codigo_area' => '+55']);
        Pais::create(['id' => 256, 'nome' => 'Zâmbia', 'codigo_area' => '+55']);
        Pais::create(['id' => 257, 'nome' => 'Zimbabué', 'codigo_area' => '+55']);
    }
}
